
#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba32f) uniform image2D postProcessImage;

layout (set = 1, binding = 0) readonly buffer myParams {
    vec3 color;
    float strength;
} tintData;

void main()	{
    vec3 pixelColor = imageLoad(postProcessImage, ivec2(gl_GlobalInvocationID.xy)).rgb * tintData.color * tintData.strength;
    imageStore(postProcessImage, ivec2(gl_GlobalInvocationID.xy), vec4(pixelColor, 1.0));
}